### ISSUE TITLE
Queue attempts to send jobs to disconnected resources

### ISSUE THREAD

**Issue by emperorcow** [jmmcatee/cracklord#23]
When a resource is disconnected, the queue attempts to send a job to it and then doesn't try the next successful resource.   Here is a log from the keeper: 

2015/03/30 10:29:23 ----Queue Keeper is running....
2015/03/30 10:29:23 ----Getting Queue Lock
2015/03/30 10:29:23 ----Updating the the Queue
2015/03/30 10:29:23 ==Res(5b1baa61-9f1c-4f96-8657-0add7b19c7dc): gpu:%!b(bool=true)
2015/03/30 10:29:23 Starting a new job on:5b1baa61-9f1c-4f96-8657-0add7b19c7dc
2015/03/30 10:29:23 connection is shut down
2015/03/30 10:29:23 ==Res(8b732cd3-76ef-4130-abca-e59d66b45fc7): gpu:%!b(bool=true)
2015/03/30 10:29:23 ----Releasing the lock

**Comment by emperorcow** [comment]
Further testing identified that this also occurs if a resource has been shut down and put in a "quit" state.

**Comment by emperorcow** [comment]
Further log info when deleting the resource, the job now appears to enter a state where the queue doesn't attempt to restart it anymore. 

2015/03/30 10:32:23 ==Res(5b1baa61-9f1c-4f96-8657-0add7b19c7dc): gpu:%!b(bool=true)
2015/03/30 10:32:23 Starting a new job on:5b1baa61-9f1c-4f96-8657-0add7b19c7dc
2015/03/30 10:32:23 connection is shut down
2015/03/30 10:32:23 ==Res(8b732cd3-76ef-4130-abca-e59d66b45fc7): gpu:%!b(bool=true)
2015/03/30 10:32:23 ----Releasing the lock
[negroni] Started DELETE /api/resources/5b1baa61-9f1c-4f96-8657-0add7b19c7dc
[negroni] Completed 200 OK in 0
2015/03/30 10:32:53 ----Queue Keeper is running....
2015/03/30 10:32:53 ----Getting Queue Lock
2015/03/30 10:32:53 ----Updating the the Queue
2015/03/30 10:32:53 ==Res(8b732cd3-76ef-4130-abca-e59d66b45fc7): gpu:%!b(bool=true)
2015/03/30 10:32:53 ----Releasing the lock
[negroni] Started GET /api/jobs
[negroni] Completed 200 OK in 1.0006ms
2015/03/30 10:33:23 ----Queue Keeper is running....
2015/03/30 10:33:23 ----Getting Queue Lock
2015/03/30 10:33:23 ----Updating the the Queue
2015/03/30 10:33:23 ==Res(8b732cd3-76ef-4130-abca-e59d66b45fc7): gpu:%!b(bool=true)
2015/03/30 10:33:23 ----Releasing the lock
2015/03/30 10:33:53 ----Queue Keeper is running....
2015/03/30 10:33:53 ----Getting Queue Lock
2015/03/30 10:33:53 ----Updating the the Queue
2015/03/30 10:33:53 ==Res(8b732cd3-76ef-4130-abca-e59d66b45fc7): gpu:%!b(bool=true)
2015/03/30 10:33:53 ----Releasing the lock

**Comment by emperorcow** [comment]
When trying to delete the job, the API returns some odd information and the following stack trace: 

[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 125 [running]:
github.com/codegangsta/negroni.func·003()
        C:/users/lucas/go/src/github.com/codegangsta/negroni/recovery.go:34 +0x114
net/rpc.(*Client).send(0x0, 0xc0821383c0)
        C:/Go/src/net/rpc/client.go:72 +0x3b6
net/rpc.(*Client).Go(0x0, 0x8976d0, 0xe, 0x7fb960, 0xc082057500, 0x7239c0, 0xc0821641e0, 0xc082160d80, 0xc082057500)

        C:/Go/src/net/rpc/client.go:309 +0x145
net/rpc.(*Client).Call(0x0, 0x8976d0, 0xe, 0x7fb960, 0xc082057500, 0x7239c0, 0xc0821641e0, 0x0, 0x0)
        C:/Go/src/net/rpc/client.go:315 +0xac
github.com/jmmcatee/cracklord/queue.(*Queue).QuitJob(0xc0820901a0, 0xc0820ca8ce, 0x24, 0x0, 0x0)
        C:/users/lucas/go/src/github.com/jmmcatee/cracklord/queue/queue.go:197 +0x698
main.(*AppController).UpdateJob(0xc082090180, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/jmmcatee/cracklord/server/req_functions.go:468 +0x9c9
main.*AppController.UpdateJob·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/jmmcatee/cracklord/server/req_functions.go:48 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc08208d2c0, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/Go/src/net/http/server.go:1265 +0x48
github.com/gorilla/mux.(*Router).ServeHTTP(0xc082002c30, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/codegangsta/negroni.func·001(0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112da0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:41 +0x5e
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc08208d670, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112da0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:24 +0x52
github.com/codegangsta/negroni.middleware.ServeHTTP(0x23a2720, 0xc08208d670, 0xc08207d0e0, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xbf
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x5e
github.com/unrolled/secure.(*Secure).HandlerFuncWithNext(0xc08206a000, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112d60)
        C:/users/lucas/go/src/github.com/unrolled/secure/secure.go:108 +0x95
github.com/unrolled/secure.*Secure.HandlerFuncWithNext·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112d60)
        C:/users/lucas/go/src/github.com/jmmcatee/cracklord/server/server.go:160 +0x56
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc08200b120, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112d60)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:24 +0x52
github.com/codegangsta/negroni.middleware.ServeHTTP(0x23a2720, 0xc08200b120, 0xc08207d0c0, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xbf
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x5e
github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc082059ce0, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112d40)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/static.go:30 +0x9b5
github.com/codegangsta/negroni.middleware.ServeHTTP(0x23a26f8, 0xc082059ce0, 0xc08207d0a0, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xbf
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x5e
github.com/codegangsta/negroni.(*Logger).ServeHTTP(0xc082044088, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112d00)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/logger.go:25 +0x1d5
github.com/codegangsta/negroni.middleware.ServeHTTP(0x23a26d0, 0xc082044088, 0xc08207d080, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xbf
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x5e
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc082005a00, 0x23ac060, 0xc0820ca940, 0xc0820229c0, 0xc082112ce0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/recovery.go:45 +0x93
github.com/codegangsta/negroni.middleware.ServeHTTP(0x23a26a8, 0xc082005a00, 0xc08207d060, 0x23ac060, 0xc0820ca940, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xbf
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc082059d40, 0x23abfc8, 0xc0820c2320, 0xc0820229c0)
        C:/users/lucas/go/src/github.com/codegangsta/negroni/negroni.go:73 +0x144
net/http.serverHandler.ServeHTTP(0xc082054600, 0x23abfc8, 0xc0820c2320, 0xc0820229c0)
        C:/Go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc0820c21e0)
        C:/Go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:1751 +0x365

**Comment by emperorcow** [comment]
I tested this, jobs no longer appear to go to "quit" resources.
