### ISSUE TITLE
Null pointer exception 

### ISSUE THREAD

**Issue by emperorcow** [jmmcatee/cracklord#37]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x639eaf]

goroutine 25 [running]:
net/rpc.(*Client).send(0x0, 0xc2081915e0)
        /usr/local/go/src/net/rpc/client.go:72 +0x3af
net/rpc.(*Client).Go(0x0, 0x8c7e30, 0x10, 0x809260, 0xc208196200, 0x72f8a0, 0xc2081ca870, 0xc208084d20, 0xc208196200)
        /usr/local/go/src/net/rpc/client.go:309 +0x13e
net/rpc.(*Client).Call(0x0, 0x8c7e30, 0x10, 0x809260, 0xc208196200, 0x72f8a0, 0xc2081ca870, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:315 +0xa5
github.com/jmmcatee/cracklord/queue.(*Queue).updateQueue(0xc2080801a0)
        /usr/local/cracklord/src/github.com/jmmcatee/cracklord/queue/queue.go:684 +0x385
github.com/jmmcatee/cracklord/queue.func·001()
        /usr/local/cracklord/src/github.com/jmmcatee/cracklord/queue/queue.go:573 +0x1e7
created by github.com/jmmcatee/cracklord/queue.(*Queue).keeper
        /usr/local/cracklord/src/github.com/jmmcatee/cracklord/queue/queue.go:669 +0x8c

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080d7f70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080d7f70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080d7f10, 0x0, 0x7f18c0697d48, 0xc2082089e0)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c050, 0xc2082089c0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20802c050, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
crypto/tls.(*listener).Accept(0xc208117ee0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/tls.go:46 +0x6b
net/http.(*Server).Serve(0xc2080849c0, 0x7f18c069b918, 0xc208117ee0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServeTLS(0xc2080849c0, 0x8aad10, 0x8, 0x8aacf0, 0x8, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1879 +0x55b
net/http.ListenAndServeTLS(0xc20800b980, 0xb, 0x8aad10, 0x8, 0x8aacf0, 0x8, 0x7f18c0699a78, 0xc2080564e0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1841 +0xef
main.main()
        /usr/local/cracklord/src/github.com/jmmcatee/cracklord/queueserver/queueserver.go:215 +0x21e4

goroutine 33 [syscall, 887 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 107 [IO wait]:
net.(*pollDesc).Wait(0xc2081ec300, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081ec300, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081ec2a0, 0xc2080de800, 0x800, 0x800, 0x0, 0x7f18c0697d48, 0xc2082095a0)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c068, 0xc2080de800, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2080e90b0, 0x7f18c069bad8, 0xc20802c068, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20807c580, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20807c580, 0xc20816d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080dc0e8, 0xc20816d000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080fa6c0, 0xc20816d000, 0x1000, 0x1000, 0x800, 0x0, 0x0)
        /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081ba180)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081ba180, 0xc2080e910a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081ba180, 0x0, 0x0, 0x0, 0xc2080e9100, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc208201b60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc208201b60, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081ba180, 0xc2081c0410, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2080dc0a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2080dc0a0)
        /usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by emperorcow** [comment]
Merging with #36, this error is related to being unable to connect to the resource server.  We need to add the logic to reconnect and remove the resource server.
